Changed DRIVEDOCS.1.3v0.1 to SHALL per RFC Comment 178
cisagov/ScubaGoggles pull request #183
Opened 2024-02-08 11:10 UTC by jkaufman-mitre

## 🗣 Description ##

Changed DRIVEDOCS.1.3v0.1 from a SHOULD to a SHALL.

Fixes #178 

### 💭 Motivation and context

Came from an RFC Comment

## 🧪 Testing

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] If applicable, *All* future TODOs are captured in issues, which are referenced in the PR description.
- [ ] The relevant issues PR resolves are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read and agree to the [CONTRIBUTING.md](https://github.com/cisagov/ScubaGoggles/blob/main/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge Checklist

- [ ] This PR has been smoke tested to ensure main is in a functional state when this PR is merged.
- [ ] Squash all commits into one PR level commit using the `Squash and merge` button.

## ✅ Post-merge Checklist

- [ ] Delete the branch to clean up.
- [ ] Close issues resolved by this PR if the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) did not activate.

2024-02-16 20:13 UTC, LaurenBassett approved these changes
One word change. No problem

2024-02-16 22:27 UTC, adhilto requested changes
Don't forget to change the last modified date

2024-02-19 11:22 UTC, jkaufman-mitre commented
The Last Modified date was fixed.

2024-02-19 16:26 UTC, adhilto approved these changes

2024-02-19 16:27 UTC, merged