Detailed Report Messages for Meet
cisagov/ScubaGoggles pull request #211
Opened 2024-03-02 01:58 UTC by rgbrow1949

Closes #174 

Added detailed report messages to meet, and refactored all correct unit tests. 

I still need to refactor the incorrect unit tests.

2024-03-07 01:55 UTC, rgbrow1949 commented
Unit tests are completed.

2024-03-12 17:12 UTC, snarve requested changes
Pulled the latest from the branch and there were merge conflicts, might need to merge the latest from main into the branch and resolve the conflicts.

2024-03-12 17:24 UTC, adhilto commented
> Pulled the latest from the branch and there were merge conflicts, might need to merge the latest from main into the branch and resolve the conflicts.

This branch actually doesn't conflict with main. Github would let us know if there were conflicts, on this page down where it currently says, "All checks have passed."

That said, I think I know what happened to you, a similar thing happened to me. If you pulled the branch locally earlier, then try to pull again now, the current branch likely conflicts with the earlier version. The easiest way (that I know of) to resolve that is to just delete your local version and pull again. This is what I did (though it's worth recognizing again that there's probably a better way, but this did do the trick):
![image](https://github.com/cisagov/ScubaGoggles/assets/106177711/fe41f83a-4297-4611-b7a7-026cf15f4668)

2024-03-12 17:35 UTC, snarve commented
> > Pulled the latest from the branch and there were merge conflicts, might need to merge the latest from main into the branch and resolve the conflicts.
> 
> This branch actually doesn't conflict with main. Github would let us know if there were conflicts, on this page down where it currently says, "All checks have passed."
> 
> That said, I think I know what happened to you, a similar thing happened to me. If you pulled the branch locally earlier, then try to pull again now, the current branch likely conflicts with the earlier version. The easiest way (that I know of) to resolve that is to just delete your local version and pull again. This is what I did (though it's worth recognizing again that there's probably a better way, but this did do the trick): ![image](https://private-user-images.githubusercontent.com/106177711/312177189-fe41f83a-4297-4611-b7a7-026cf15f4668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjQ4NTQsIm5iZiI6MTcxMDI2NDU1NCwicGF0aCI6Ii8xMDYxNzc3MTEvMzEyMTc3MTg5LWZlNDFmODNhLTQyOTctNDYxMS1iN2E3LTAyNmNmMTVmNDY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNzI5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjliMTAxNDA2NjJlMjJkNzAwMDQ1YjU2OTdkODZhMjVjNWZhZTM4NGQ4MDhmZDMzM2VjNzkwMzU1NWE5ZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3uRFpFdQt881-Mv9ClHIwvSkON_Kxf_6fHWD4WRp1u4)

yeah I tried resolving the conflicts but didn't work. yes it did conflict with the earlier version of the branch. was saving deleting the branch as the last resort. will delete the branch and test. Thanks for the update.

2024-03-12 17:45 UTC, snarve commented
> > > Pulled the latest from the branch and there were merge conflicts, might need to merge the latest from main into the branch and resolve the conflicts.
> > 
> > 
> > This branch actually doesn't conflict with main. Github would let us know if there were conflicts, on this page down where it currently says, "All checks have passed."
> > That said, I think I know what happened to you, a similar thing happened to me. If you pulled the branch locally earlier, then try to pull again now, the current branch likely conflicts with the earlier version. The easiest way (that I know of) to resolve that is to just delete your local version and pull again. This is what I did (though it's worth recognizing again that there's probably a better way, but this did do the trick): ![image](https://private-user-images.githubusercontent.com/106177711/312177189-fe41f83a-4297-4611-b7a7-026cf15f4668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjQ4NTQsIm5iZiI6MTcxMDI2NDU1NCwicGF0aCI6Ii8xMDYxNzc3MTEvMzEyMTc3MTg5LWZlNDFmODNhLTQyOTctNDYxMS1iN2E3LTAyNmNmMTVmNDY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxNzI5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjliMTAxNDA2NjJlMjJkNzAwMDQ1YjU2OTdkODZhMjVjNWZhZTM4NGQ4MDhmZDMzM2VjNzkwMzU1NWE5ZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3uRFpFdQt881-Mv9ClHIwvSkON_Kxf_6fHWD4WRp1u4)
> 
> yeah I tried resolving the conflicts but didn't work. yes it did conflict with the earlier version of the branch. was saving deleting the branch as the last resort. will delete the branch and test. Thanks for the update.

cool, it worked out

2024-03-12 17:45 UTC, snarve approved these changes

2024-03-12 18:00 UTC, adhilto requested changes
Functionally works exactly as expected :100:. Just a few style things I'd recommend.

2024-03-12 18:00 UTC, adhilto commented on rego/Meet.rego
> +
Recommend deleting stale code that isn't used anywhere
 ```suggestion
```

2024-03-12 18:00 UTC, adhilto commented on rego/Meet.rego
> +
Stale code
```suggestion
```

2024-03-12 18:00 UTC, adhilto commented on rego/Meet.rego
> +
```suggestion
```

2024-03-12 18:00 UTC, adhilto commented on rego/Meet.rego
> +
```suggestion
```

2024-03-12 18:00 UTC, adhilto commented on rego/Meet.rego
> +    "ReportDetails": utils.ReportDetails(NonCompliantOUs1_1, []),
Recommend adding a comment like this at least for the first setting, just so it's easier to understand what's going on.
```suggestion
    # Empty list in next line for non-compliant groups, as Meet settings can't be changed at the group level
    "ReportDetails": utils.ReportDetails(NonCompliantOUs1_1, []),
```

2024-03-12 21:47 UTC, adhilto approved these changes

2024-03-12 21:48 UTC, merged