[#84] Detailed report message Gmail
cisagov/ScubaGoggles pull request #278
Opened 2024-05-09 20:04 UTC by snarve

## 🗣 Description ##

This PR covers adding the Detailed report message feature for Gmail and also the Group override policy.
Gmail policies cannot be controlled at Group level, so no changes there
Also, covered in this PR, updates to the rego code to refer to the updated 'FilterEventsOU' 

### 💭 Motivation and context

Closes #84 , #197, #75

## 🧪 Testing

- Ensure the report results are as expected for Gmail policies
- All unit tests should pass

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] If applicable, *All* future TODOs are captured in issues, which are referenced in the PR description.
- [ ] The relevant issues PR resolves are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read and agree to the [CONTRIBUTING.md](https://github.com/cisagov/ScubaGoggles/blob/main/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge Checklist

- [ ] This PR has been smoke tested to ensure main is in a functional state when this PR is merged.
- [ ] Squash all commits into one PR level commit using the `Squash and merge` button.

## ✅ Post-merge Checklist

- [ ] Delete the branch to clean up.
- [ ] Close issues resolved by this PR if the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) did not activate.

2024-05-10 20:28 UTC, adhilto requested changes

2024-05-10 20:28 UTC, adhilto commented on rego/Gmail.rego
>  #--
POP access actually can be controlled at the group level, not just the OU.

2024-05-10 20:28 UTC, adhilto commented on rego/Gmail.rego
>  #--
IMAP access actually can be controlled at the group level, not just the OU.

2024-05-10 20:28 UTC, adhilto commented on rego/Gmail.rego
> +        "Automatically enable outbound relay is set to",
Recommend tweaking to match the wording used in the baseline and UI
```suggestion
        "Allow per-user outbound gateways is set to",
```

2024-05-10 20:28 UTC, adhilto commented on rego/Gmail.rego
> +        "Warning from untrusted recipient is set to",
Tweak for baseline/UI consistency.
```suggestion
        "Warn for external participants is set to",
```

2024-05-10 20:28 UTC, adhilto commented on rego/Gmail.rego
> +        "Delay Delivery for suspicious email is set to",
Tweak for baseline/UI consistency.
```suggestion
        "Enhanced pre-delivery message scanning is set to",
```

2024-05-10 20:28 UTC, adhilto commented on rego/Gmail.rego
>  #--
The output of this test is swapped: if I enable pre-delivery scanning, the test fails. If I disable it, the test passes.

2024-05-10 20:28 UTC, adhilto commented on rego/Gmail.rego
> +        "Deep Scaning for email attachments is set to",
Tweak for baseline/UI consistency.
```suggestion
        "Security sandbox is",
```

2024-05-29 21:40 UTC, adhilto commented on rego/Gmail.rego
> +        "Links and external images safety to scan linked images is set to",
```suggestion
        "Scan linked images is",
```

2024-05-29 21:41 UTC, adhilto commented on rego/Gmail.rego
> +        "Links and external images safety show warning prompt for click on links to untrusted domains is set to",
```suggestion
        "Show warning prompt for click on links to untrusted domains is",
```

2024-05-31 05:20 UTC, adhilto approved these changes

2024-06-02 21:21 UTC, LaurenBassett commented on rego/Calendar.rego
Seconding. Is it possible it was to avoid a merge conflict with another branch?

2024-06-02 21:22 UTC, LaurenBassett reviewed
Everything looks good to me. Want to figure out why those two comments are deleted before merging but everything else looks fine

2024-06-03 15:14 UTC, snarve commented on rego/Chat.rego
This method was added prior to the GetFriendlyValue methods and the code is refactored there on. Removed this method since it is not used anymore and didn't have any other references. Is it causing a merge conflict?

2024-06-03 15:19 UTC, snarve commented on rego/Calendar.rego
Added back the comment for consistency

2024-06-03 15:19 UTC, adhilto commented on rego/Chat.rego
I agree with its removal. It's not causing a conflict, I think it just seemed out of place in the PR. Ideally the change would have been made in its own PR, but at this point I kinda don't think it would be worth the effort to make that happen. So my vote would be to leave this as is.

2024-06-03 15:23 UTC, snarve commented on rego/Chat.rego
Yeah, agreed this is ideally not the place to make this change.
Came across this when was referring to Chat for some detailed report message examples and ran into this method, figured out this was a left over method so removed it since it was not affecting anything.

2024-06-03 15:26 UTC, snarve commented on rego/Calendar.rego
also about this OU related comment, I recollect there was a discussion on removing this comment, but not sure why I removed only one and again preferably having its own PR would be more efficient as @adhilto mentioned, so for now adding it back

2024-06-03 18:09 UTC, merged