Clarifying Implementation Steps of CommonControls13.1
cisagov/ScubaGoggles pull request #445
Opened 2024-10-02 15:01 UTC by mdueltgen

## 🗣 Description ##

Updated 13.1 steps for editing rules for clarity.

### 💭 Motivation and context

Closes #419
Based on Internal Discussion about clarifying steps for rule configuration polices

## 🧪 Testing

N/A no code changes.

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] If applicable, *All* future TODOs are captured in issues, which are referenced in the PR description.
- [ ] The relevant issues PR resolves are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read and agree to the [CONTRIBUTING.md](https://github.com/cisagov/ScubaGoggles/blob/main/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge Checklist

- [ ] This PR has been smoke tested to ensure main is in a functional state when this PR is merged.
- [ ] Squash all commits into one PR level commit using the `Squash and merge` button.

## ✅ Post-merge Checklist

- [ ] Delete the branch to clean up.
- [ ] Close issues resolved by this PR if the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) did not activate.

2024-10-02 20:50 UTC, adhilto requested changes
Two minor things:

2024-10-02 21:02 UTC, mdueltgen commented on baselines/commoncontrols.md
> +13. Review the updated rule details, and then click **Update Rule**.
Ahh got it, I wasn't sure how to do that in markdown.

2024-10-02 21:16 UTC, adhilto commented on baselines/commoncontrols.md
> +7.  A list of system defined rules displays. For each of the rules from listed above, edit the configuration:
Looks good! One more thing, sorry I didn't notice this the first time, there's a small typo:
```suggestion
7.  A list of system defined rules displays. For each of the rules listed above, edit the configuration:
```

2024-10-03 14:01 UTC, adhilto approved these changes

2024-10-03 14:14 UTC, merged